{
 "title": "SolarBOB",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "RP", "query": "show retention policies" }
  ]
 },
 "panels": [
  {
   "title": "Current Power",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power",
     "select": [
      [
       { "params": [ "PPV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Yield today",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "today",
     "select": [
      [
       { "params": [ "H20" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Power Today",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "today",
     "select": [
      [
       { "params": [ "H21" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Yield per day",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "today",
     "query": "SELECT max(\"H20\") FROM \"today\" WHERE $timeFilter GROUP BY time(1d) fill(null) tz('CET')",
     "select": [
      [
       { "params": [ "H20" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "UTC"
    }
   ]
  },
  {
   "title": "Voltages Smmoth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "power",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10" ], "type": "moving_average" },
       { "params": [ "battery voltage" ], "type": "alias" }
      ],
      [
       { "params": [ "VPV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10" ], "type": "moving_average" },
       { "params": [ "Panel voltage" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Leistung",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "voltamp" }
   ],
   "targets": [
    {
     "alias": "PPV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power",
     "select": [
      [
       { "params": [ "mean_PPV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "PPV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "battery voltage" ], "type": "alias" }
      ],
      [
       { "params": [ "VPV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Panel voltage" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ampere",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "mamp" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power",
     "select": [
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "battery current" ], "type": "alias" }
      ],
      [
       { "params": [ "IL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Load current" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "MPPT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "select": [
      [
       { "params": [ "MPPT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wifi Link",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(wifi_station_signal_dbm{mac=\"20:28:18:A1:2A:7E\"}[$__interval])",
     "legendFormat": "signal {{instance}} <-> nex173"
    },
    {
     "expr": "avg_over_time (wifi_network_signal_dbm{instance=\"nex173:9100\"}[$__interval])",
     "legendFormat": "[nex173] signal {{bssid}} ch:{{channel}} {{frequency}} MHz"
    },
    {
     "expr": "avg_over_time(wifi_network_bitrate{mode=\"Client\", instance=\"nex173:9100\"}[$__interval])",
     "legendFormat": "[nex173] bitrate {{bssid}} ch:{{channel}} {{frequency}} MHz"
    }
   ]
  }
 ]
}